# Some models have different codes
_LANG_CODE_MAP = {
    "en": "eng_Latn",
    "de": "deu_Latn",
    "es": "spa_Latn",
    "pt": "por_Latn",
    "ru": "rus_Cyrl",
    "uk": "ukr_Cyrl",
    "ja": "jpn_Jpan",
    "zh": "zho_Hans",
    "fr": "fra_Latn",
    "it": "ita_Latn",
    "ko": "kor_Hang",
    "tr": "tur_Latn",
    "hu": "hun_Latn",
    "hi": "hin_Deva",
    "ar": "arb_Arab",
    "bn": "ben_Beng",
    "id": "ind_Latn",
    "ur": "urd_Arab",
    "pl": "pol_Latn",
    "nl": "nld_Latn",
    "ro": "ron_Latn",
    "el": "ell_Grek",
    "cs": "ces_Latn",
    "sv": "swe_Latn",
    "bg": "bul_Cyrl",
    "da": "dan_Latn",
    "fi": "fin_Latn",
    "no": "nob_Latn",
    "sk": "slk_Latn",
    "hr": "hrv_Latn",
    "lt": "lit_Latn",
    "sl": "slv_Latn",
    "lv": "lvs_Latn",
}